[package]
name = "diesel_bug"
version = "0.1.0"
authors = ["Pyry Kontio <pyry.kontio@drasa.eu>"]

[dependencies]
diesel = { version = "0.8"}
diesel_codegen = {version = "0.8", default-features = false, features = ["postgres", "dotenv"] }
dotenv = "0.8"
dotenv_macros = "0.9"
